package httpapi

// RouteEntry documents a public HTTP route (lightweight substitute until OpenAPI).
type RouteEntry struct {
	Method      string `json:"method"`
	Path        string `json:"path"`
	Description string `json:"description"`
}

func routeCatalog() []RouteEntry {
	return []RouteEntry{
		{"GET", "/api/health", "Liveness check (no auth)"},
		{"GET", "/api/version", "Build version: full describe string, parsed tag, semver number, commits_after_tag, commit hash, dirty (no auth)"},
		{"GET", "/api/ops/summary", "Operator snapshot: expected SQLite schema version, build version/commit, product active vs soft-deleted counts (no auth)"},
		{"GET", "/api/ops/host-metrics", "Host CPU (short sample), memory, root disk usage; load averages when supported (no auth); uses gopsutil"},
		{"GET", "/api/docs/routes", "This route list (JSON)"},
		{"POST", "/api/products", "Register product (optional repo_url, repo_clone_path, repo_branch, description, program_document, settings_json, icon_url, merge_policy_json)"},
		{"GET", "/api/products", "List active products; ?include_deleted=1|true includes soft-deleted (deleted_at on each row)"},
		{"GET", "/api/products/{id}", "Get product (includes merge_policy object, merge_queue_pending when merge queue wired)"},
		{"PATCH", "/api/products/{id}", "Patch product metadata (MC-style profile fields); optional mission_statement, vision_statement; operations_log product.patch"},
		{"DELETE", "/api/products/{id}", "Soft-delete product (sets deleted_at; hidden from list/get and autopilot); operations_log product.soft_delete; 409 if already deleted"},
		{"POST", "/api/products/{id}/restore", "Clear soft-delete; operations_log product.restore; 409 if not deleted"},
		{"POST", "/api/products/{id}/research", "Run research phase"},
		{"POST", "/api/products/{id}/ideation", "Run ideation phase"},
		{"GET", "/api/products/{id}/ideas", "List ideas for product"},
		{"POST", "/api/products/{id}/nlp/tfidf-suggest-tags", "TF-IDF tag suggestions for text or idea_id against other ideas on product (optional extra_corpus); no LLM"},
		{"GET", "/api/products/{id}/maybe-pool", "List ideas in maybe pool for product"},
		{"GET", "/api/products/{id}/swipe-history", "Swipe audit log for product (?limit= default 100, max 500)"},
		{"POST", "/api/products/{id}/knowledge", "Create knowledge entry {content, task_id?, metadata?}; auto-ingest from swipes/feedback/completion when ARMS_KNOWLEDGE_AUTO_INGEST on; SQLite FTS5 or chromem + dispatch-time injection into OpenClaw"},
		{"GET", "/api/products/{id}/knowledge", "List (?limit=) or search (?q= keyword/FTS); ?q= uses FTS5 on SQLite, substring rank in memory"},
		{"GET", "/api/products/{id}/knowledge/{entryId}", "Get knowledge row by integer id"},
		{"PATCH", "/api/products/{id}/knowledge/{entryId}", "Update {content?, metadata?} — at least one field"},
		{"DELETE", "/api/products/{id}/knowledge/{entryId}", "Delete knowledge row"},
		{"POST", "/api/products/{id}/preference-model/recompute", "Aggregate swipe_history + product_feedback + maybe_pool into preference_models JSON (?limit= default 500)"},
		{"GET", "/api/products/{id}/preference-model", "Preference model JSON: dedicated row when set, else legacy products.preference_model_json (response includes source)"},
		{"PUT", "/api/products/{id}/preference-model", "Upsert dedicated preference_models row {model_json}"},
		{"GET", "/api/products/{id}/product-schedule", "product_schedules row or defaults: enabled, spec_json, cron_expr, delay_seconds, asynq_task_id, last/next scheduled timestamps, updated_at"},
		{"PATCH", "/api/products/{id}/product-schedule", "Upsert schedule {enabled?, spec_json?, cron_expr?, delay_seconds?} — at least one field; gates TickScheduled; when Redis set, cron/delay enqueue product:schedule:tick on worker"},
		{"GET", "/api/products/{id}/research-cycles", "Research run history snapshots (?limit= default 50, max 500); empty until research runs with persistence"},
		{"GET", "/api/products/{id}/tasks", "List tasks for product (Kanban source, newest first)"},
		{"GET", "/api/products/{id}/costs/breakdown", "Cost breakdown (?from=&to= RFC3339) + by_agent / by_model"},
		{"PATCH", "/api/products/{id}/cost-caps", "Patch daily/monthly/cumulative caps (negative value clears a limit)"},
		{"GET", "/api/products/{id}/convoys", "List convoys for product (newest first)"},
		{"GET", "/api/products/{id}/merge-queue", "List pending merge-queue rows (FIFO): head_task_id, pending_count, per-row queue_position, is_head; ?limit= default 50, max 500"},
		{"GET", "/api/products/{id}/agent-health", "List task agent heartbeats for product (?limit= default 100, max 500)"},
		{"GET", "/api/products/{id}/stalled-tasks", "Tasks expecting agent heartbeats with none or stale heartbeat (?stale_sec= overrides default)"},
		{"GET", "/api/products/{id}/chat-queue", "Pending operator-queued notes across tasks (?limit=); SSE task_chat_message / task_chat_queue_ack"},
		{"POST", "/api/products/{id}/chat-queue/{messageId}/ack", "Clear queue_pending on a queued message (must belong to product); operations_log task_chat.queue_ack"},
		{"PATCH", "/api/ideas/{id}", "Update idea MC metadata (category, scores, tags, notes, …); at least one field"},
		{"POST", "/api/ideas/{id}/swipe", "Submit swipe decision"},
		{"POST", "/api/ideas/{id}/promote-maybe", "Promote a maybe idea to yes (and advance product from swipe when applicable)"},
		{"POST", "/api/tasks", "Create task from approved idea (Kanban planning)"},
		{"GET", "/api/tasks/{id}", "Get task"},
		{"PATCH", "/api/tasks/{id}", "Update Kanban status / status_reason / planning clarifications JSON"},
		{"POST", "/api/tasks/{id}/plan/approve", "Approve plan → inbox (optional body {spec})"},
		{"POST", "/api/tasks/{id}/plan/reject", "Reject / recall plan → planning (inbox or assigned pre-dispatch; optional {status_reason})"},
		{"POST", "/api/tasks/{id}/dispatch", "Dispatch to agent gateway (requires assigned + approved plan)"},
		{"POST", "/api/tasks/{id}/merge-queue", "Enqueue task for serialized merge (409 if already pending); operations_log merge_queue.enqueue"},
		{"DELETE", "/api/tasks/{id}/merge-queue", "Remove pending row for task (non-head always; head only when no active merge lease); 503 merge_lease_busy if ship in flight; operations_log merge_queue.cancel"},
		{"POST", "/api/tasks/{id}/merge-queue/complete", "Complete merge queue head; optional ?skip_ship=1 skips forge/git merge; with ARMS_MERGE_BACKEND=github|local runs real merge (409 merge_conflict, 503 merge_lease_busy); operations_log merge_queue.complete"},
		{"POST", "/api/tasks/{id}/merge-queue/resolve", "After conflict: body {action: retry_merge|skip_ship} (default retry_merge); same ship semantics as merge-queue/complete; operations_log merge_queue.resolve"},
		{"POST", "/api/merge-queue/{id}/resolve", "Same as task resolve but {id} is workspace_merge_queue row id from GET .../merge-queue; operations_log merge_queue.resolve"},
		{"POST", "/api/tasks/{id}/workspace/git-worktree", "Optional git worktree add (ARMS_ENABLE_GIT_WORKTREES=1, ARMS_WORKSPACE_ROOT, product.repo_clone_path); body {branch}"},
		{"GET", "/api/tasks/{id}/agent-health", "Agent heartbeat row for task (unknown if never reported)"},
		{"PATCH", "/api/tasks/{id}/agent-health", "Record heartbeat {status, detail?}"},
		{"POST", "/api/tasks/{id}/pull-request", "Open GitHub PR (head_branch, optional title/body; product.repo_url; ARMS_GITHUB_TOKEN or ARMS_GITHUB_PR_BACKEND=gh + gh CLI)"},
		{"GET", "/api/tasks/{id}/checkpoints", "List checkpoint history (?limit=)"},
		{"POST", "/api/tasks/{id}/checkpoint/restore", "Restore checkpoint from history {history_id}"},
		{"POST", "/api/tasks/{id}/checkpoint", "Record checkpoint"},
		{"POST", "/api/tasks/{id}/complete", "Mark task completed"},
		{"POST", "/api/tasks/{id}/stall-nudge", "Operator stall nudge (optional {note}); execution statuses only; SSE task_stall_nudged"},
		{"GET", "/api/tasks/{id}/convoy", "Mission Control–shape convoy by parent task id (nested task per subtask, mc_compat in metadata_json); 404 No convoy found for this task"},
		{"POST", "/api/tasks/{id}/convoy", "MC create: {strategy?, name?, subtasks[{title, description?, suggested_role?, agent_id?, depends_on?}], decomposition_spec?}; strategy ai → 501; conflict if convoy exists; may move task to convoy_active"},
		{"PATCH", "/api/tasks/{id}/convoy", "MC status: {status} merged into metadata_json.mc_compat"},
		{"DELETE", "/api/tasks/{id}/convoy", "Delete convoy; {success:true}; may move convoy_active parent to inbox"},
		{"GET", "/api/tasks/{id}/convoy/progress", "MC progress: breakdown by synthetic task status + subtask summary"},
		{"POST", "/api/tasks/{id}/convoy/dispatch", "MC dispatch wave: body {estimated_cost?}; respects mc_compat.status pause; returns {dispatched,total,results[]}"},
		{"POST", "/api/tasks/{id}/convoy/subtasks", "MC append: {subtasks:[…]}; 201 array of new rows (MC-shaped)"},
		{"POST", "/api/tasks/{id}/chat", "Append per-task chat {body, author?: operator|agent|system, queue?: bool}; queue=true leaves note on product chat-queue; SSE task_chat_message"},
		{"GET", "/api/tasks/{id}/chat", "Chronological chat history (?limit= default 200, max 500)"},
		{"POST", "/api/convoys", "Create convoy {parent_task_id, product_id, metadata_json?, subtasks[{id?, agent_role, title?, metadata_json?, depends_on?}]}"},
		{"GET", "/api/convoys/{id}", "Get convoy by id (metadata_json, graph summary, edges[] from depends_on, subtask dag_layer + status; SQLite also persists convoy_edges)"},
		{"GET", "/api/convoys/{id}/graph", "Convoy DAG: topological_order (stable), edges[], layers[] (dag_layer buckets), graph summary"},
		{"GET", "/api/convoys/{id}/mail", "Inter-subtask mail (?limit=); 503 if mail store not wired"},
		{"POST", "/api/convoys/{id}/mail", "Append mail {body, subtask_id|from_subtask_id, to_subtask_id?, kind?: note|handoff|blocker}"},
		{"POST", "/api/convoys/{id}/dispatch-ready", "Dispatch ready convoy subtasks; JSON {estimated_cost} per subtask for budget.Composite (same as task dispatch; empty body treats as 0). When AgentHealth for the parent task is error-like (stalled/error/failed/offline), no-op success. Gateway failures increment subtask dispatch_attempts until cap (default 5), then 502."},
		{"POST", "/api/convoy", "MC alias: same as POST /api/convoys"},
		{"GET", "/api/convoy/{id}", "MC alias: same as GET /api/convoys/{id}"},
		{"GET", "/api/convoy/{id}/graph", "MC alias: same as GET /api/convoys/{id}/graph"},
		{"GET", "/api/convoy/{id}/mail", "MC alias: same as GET /api/convoys/{id}/mail"},
		{"POST", "/api/convoy/{id}/mail", "MC alias: same as POST /api/convoys/{id}/mail"},
		{"POST", "/api/convoy/{id}/dispatch-ready", "MC alias: same as POST /api/convoys/{id}/dispatch-ready"},
		{"POST", "/api/costs", "Record cost event"},
		{"GET", "/api/agents", "registry[] execution agents + items[] recent task heartbeats (stub:true on items only when agent health disabled)"},
		{"POST", "/api/agents", "Register execution agent {display_name, optional product_id, source, external_ref}"},
		{"GET", "/api/agents/{id}/mailbox", "List mailbox messages (?limit=)"},
		{"POST", "/api/agents/{id}/mailbox", "Append mailbox {body, optional task_id}"},
		{"POST", "/api/openclaw/proxy", "Gateway proxy (stub)"},
		{"GET", "/api/workspaces", "Workspace snapshot: allocated ports + merge_queue_pending"},
		{"GET", "/api/operations-log", "Audit log (?limit=, ?product_id=, ?action=, ?resource_type=, ?since= RFC3339)"},
		{"GET", "/api/settings", "Settings (stub)"},
		{"POST", "/api/nlp/tfidf-suggest-tags", "Stateless TF-IDF tag suggestions: JSON { text, corpus[]?, top_k?, min_token_len? }; no LLM"},
		{"POST", "/api/webhooks/agent-completion", "Agent completion (HMAC); body task_id; optional next_board_status testing|review for full_auto/semi_auto Kanban advance; optional convoy_id+subtask_id for subtask completion"},
		{"POST", "/api/webhooks/ci-completion", "CI completion (HMAC, same WEBHOOK_SECRET); body task_id, next_board_status testing|review|done|failed; optional status_reason (default reason when failed if empty)"},
		{"GET", "/api/live/events", "SSE activity stream (Bearer or ?token= when MC_API_TOKEN; ?basic= for ARMS_ACL; ?product_id= filters)"},
	}
}
