package httpapi

// RouteEntry documents a public HTTP route (lightweight substitute until OpenAPI).
type RouteEntry struct {
	Method      string `json:"method"`
	Path        string `json:"path"`
	Description string `json:"description"`
}

func routeCatalog() []RouteEntry {
	return []RouteEntry{
		{"GET", "/api/health", "Liveness check (no auth)"},
		{"GET", "/api/docs/routes", "This route list (JSON)"},
		{"POST", "/api/products", "Register product (optional repo_url, repo_clone_path, repo_branch, description, program_document, settings_json, icon_url, merge_policy_json)"},
		{"GET", "/api/products", "List all products (newest registration order is store-defined; typically useful for dashboards)"},
		{"GET", "/api/products/{id}", "Get product (includes merge_policy object, merge_queue_pending when merge queue wired)"},
		{"PATCH", "/api/products/{id}", "Patch product metadata (MC-style profile fields); operations_log product.patch"},
		{"POST", "/api/products/{id}/research", "Run research phase"},
		{"POST", "/api/products/{id}/ideation", "Run ideation phase"},
		{"GET", "/api/products/{id}/ideas", "List ideas for product"},
		{"GET", "/api/products/{id}/maybe-pool", "List ideas in maybe pool for product"},
		{"GET", "/api/products/{id}/swipe-history", "Swipe audit log for product (?limit= default 100, max 500)"},
		{"POST", "/api/products/{id}/preference-model/recompute", "Aggregate swipe_history into preference_models JSON (?limit= default 500)"},
		{"GET", "/api/products/{id}/preference-model", "Preference model JSON: dedicated row when set, else legacy products.preference_model_json (response includes source)"},
		{"PUT", "/api/products/{id}/preference-model", "Upsert dedicated preference_models row {model_json}"},
		{"GET", "/api/products/{id}/product-schedule", "product_schedules row or defaults: enabled, spec_json, cron_expr, delay_seconds, asynq_task_id, last/next scheduled timestamps, updated_at"},
		{"PATCH", "/api/products/{id}/product-schedule", "Upsert schedule {enabled?, spec_json?, cron_expr?, delay_seconds?} — at least one field; gates TickScheduled; when Redis set, cron/delay enqueue product:schedule:tick on worker"},
		{"GET", "/api/products/{id}/research-cycles", "Research run history snapshots (?limit= default 50, max 500); empty until research runs with persistence"},
		{"GET", "/api/products/{id}/tasks", "List tasks for product (Kanban source, newest first)"},
		{"GET", "/api/products/{id}/costs/breakdown", "Cost breakdown (?from=&to= RFC3339) + by_agent / by_model"},
		{"PATCH", "/api/products/{id}/cost-caps", "Patch daily/monthly/cumulative caps (negative value clears a limit)"},
		{"GET", "/api/products/{id}/convoys", "List convoys for product (newest first)"},
		{"GET", "/api/products/{id}/merge-queue", "List pending merge-queue rows (FIFO): head_task_id, pending_count, per-row queue_position, is_head; ?limit= default 50, max 500"},
		{"GET", "/api/products/{id}/agent-health", "List task agent heartbeats for product (?limit= default 100, max 500)"},
		{"GET", "/api/products/{id}/stalled-tasks", "Tasks expecting agent heartbeats with none or stale heartbeat (?stale_sec= overrides default)"},
		{"POST", "/api/ideas/{id}/swipe", "Submit swipe decision"},
		{"POST", "/api/ideas/{id}/promote-maybe", "Promote a maybe idea to yes (and advance product from swipe when applicable)"},
		{"POST", "/api/tasks", "Create task from approved idea (Kanban planning)"},
		{"GET", "/api/tasks/{id}", "Get task"},
		{"PATCH", "/api/tasks/{id}", "Update Kanban status / status_reason / planning clarifications JSON"},
		{"POST", "/api/tasks/{id}/plan/approve", "Approve plan → inbox (optional body {spec})"},
		{"POST", "/api/tasks/{id}/plan/reject", "Reject / recall plan → planning (inbox or assigned pre-dispatch; optional {status_reason})"},
		{"POST", "/api/tasks/{id}/dispatch", "Dispatch to agent gateway (requires assigned + approved plan)"},
		{"POST", "/api/tasks/{id}/merge-queue", "Enqueue task for serialized merge (409 if already pending); operations_log merge_queue.enqueue"},
		{"DELETE", "/api/tasks/{id}/merge-queue", "Remove pending row for task (non-head always; head only when no active merge lease); 503 merge_lease_busy if ship in flight; operations_log merge_queue.cancel"},
		{"POST", "/api/tasks/{id}/merge-queue/complete", "Complete merge queue head; optional ?skip_ship=1 skips forge/git merge; with ARMS_MERGE_BACKEND=github|local runs real merge (409 merge_conflict, 503 merge_lease_busy); operations_log merge_queue.complete"},
		{"POST", "/api/tasks/{id}/merge-queue/resolve", "After conflict: body {action: retry_merge|skip_ship} (default retry_merge); same ship semantics as merge-queue/complete; operations_log merge_queue.resolve"},
		{"POST", "/api/merge-queue/{id}/resolve", "Same as task resolve but {id} is workspace_merge_queue row id from GET .../merge-queue; operations_log merge_queue.resolve"},
		{"POST", "/api/tasks/{id}/workspace/git-worktree", "Optional git worktree add (ARMS_ENABLE_GIT_WORKTREES=1, ARMS_WORKSPACE_ROOT, product.repo_clone_path); body {branch}"},
		{"GET", "/api/tasks/{id}/agent-health", "Agent heartbeat row for task (unknown if never reported)"},
		{"PATCH", "/api/tasks/{id}/agent-health", "Record heartbeat {status, detail?}"},
		{"POST", "/api/tasks/{id}/pull-request", "Open GitHub PR (head_branch, optional title/body; product.repo_url; ARMS_GITHUB_TOKEN or ARMS_GITHUB_PR_BACKEND=gh + gh CLI)"},
		{"GET", "/api/tasks/{id}/checkpoints", "List checkpoint history (?limit=)"},
		{"POST", "/api/tasks/{id}/checkpoint/restore", "Restore checkpoint from history {history_id}"},
		{"POST", "/api/tasks/{id}/checkpoint", "Record checkpoint"},
		{"POST", "/api/tasks/{id}/complete", "Mark task completed"},
		{"POST", "/api/tasks/{id}/stall-nudge", "Operator stall nudge (optional {note}); execution statuses only; SSE task_stall_nudged"},
		{"POST", "/api/convoys", "Create convoy"},
		{"GET", "/api/convoys/{id}", "Get convoy by id"},
		{"GET", "/api/convoys/{id}/mail", "Inter-subtask mail (?limit=); 503 if mail store not wired"},
		{"POST", "/api/convoys/{id}/mail", "Append mail {subtask_id, body}"},
		{"POST", "/api/convoys/{id}/dispatch-ready", "Dispatch ready convoy subtasks; JSON {estimated_cost} per subtask for budget.Composite (same as task dispatch; empty body treats as 0)"},
		{"POST", "/api/convoy", "MC alias: same as POST /api/convoys"},
		{"GET", "/api/convoy/{id}", "MC alias: same as GET /api/convoys/{id}"},
		{"POST", "/api/convoy/{id}/dispatch-ready", "MC alias: same as POST /api/convoys/{id}/dispatch-ready"},
		{"POST", "/api/costs", "Record cost event"},
		{"GET", "/api/agents", "registry[] execution agents + items[] recent task heartbeats (stub:true on items only when agent health disabled)"},
		{"POST", "/api/agents", "Register execution agent {display_name, optional product_id, source, external_ref}"},
		{"GET", "/api/agents/{id}/mailbox", "List mailbox messages (?limit=)"},
		{"POST", "/api/agents/{id}/mailbox", "Append mailbox {body, optional task_id}"},
		{"POST", "/api/openclaw/proxy", "Gateway proxy (stub)"},
		{"GET", "/api/workspaces", "Workspace snapshot: allocated ports + merge_queue_pending"},
		{"GET", "/api/operations-log", "Audit log (?limit=, ?product_id=, ?action=, ?resource_type=, ?since= RFC3339)"},
		{"GET", "/api/settings", "Settings (stub)"},
		{"POST", "/api/webhooks/agent-completion", "Agent completion (HMAC, not Bearer); body task_id + optional convoy_id + subtask_id to complete a convoy subtask without closing parent task"},
		{"GET", "/api/live/events", "SSE activity stream (Bearer or ?token= when MC_API_TOKEN; ?basic= for ARMS_ACL; ?product_id= filters)"},
	}
}
