package httpapi

import (
	"log/slog"
	"net/http"
)

// NewRouter returns the full HTTP handler tree: public routes, webhook (HMAC), SSE (query token), and Bearer-protected API.
func NewRouter(cfg Config, h *Handlers) http.Handler {
	mux := http.NewServeMux()
	mux.Handle("GET /api/health", http.HandlerFunc(h.health))
	mux.Handle("GET /api/version", http.HandlerFunc(h.version))
	mux.Handle("GET /api/ops/summary", http.HandlerFunc(h.opsSummary))
	mux.Handle("GET /api/ops/host-metrics", http.HandlerFunc(h.opsHostMetrics))
	mux.Handle("GET /api/docs/routes", http.HandlerFunc(h.routesDoc))
	mux.Handle("POST /api/webhooks/agent-completion", http.HandlerFunc(h.agentCompletionWebhook))
	mux.Handle("POST /api/webhooks/ci-completion", http.HandlerFunc(h.ciCompletionWebhook))
	mux.Handle("GET /api/live/events", SSEQueryToken(cfg, http.HandlerFunc(h.liveSSE)))

	sub := http.NewServeMux()
	sub.Handle("POST /api/products", http.HandlerFunc(h.createProduct))
	sub.Handle("GET /api/products", http.HandlerFunc(h.listProducts))
	sub.Handle("GET /api/products/{id}", http.HandlerFunc(h.getProduct))
	sub.Handle("PATCH /api/products/{id}", http.HandlerFunc(h.patchProduct))
	sub.Handle("DELETE /api/products/{id}", http.HandlerFunc(h.deleteProduct))
	sub.Handle("POST /api/products/{id}/restore", http.HandlerFunc(h.restoreProduct))
	sub.Handle("POST /api/products/{id}/research", http.HandlerFunc(h.runResearch))
	sub.Handle("POST /api/products/{id}/ideation", http.HandlerFunc(h.runIdeation))
	sub.Handle("GET /api/products/{id}/ideas", http.HandlerFunc(h.listIdeas))
	sub.Handle("POST /api/products/{id}/nlp/tfidf-suggest-tags", http.HandlerFunc(h.postProductTfidfSuggestTags))
	sub.Handle("POST /api/products/{id}/nlp/suggest-idea-id", http.HandlerFunc(h.postProductSuggestIdeaID))
	sub.Handle("GET /api/products/{id}/maybe-pool", http.HandlerFunc(h.listMaybePool))
	sub.Handle("POST /api/products/{id}/maybe-pool/batch-reeval", http.HandlerFunc(h.maybePoolBatchReeval))
	sub.Handle("POST /api/products/{id}/feedback", http.HandlerFunc(h.postProductFeedback))
	sub.Handle("GET /api/products/{id}/feedback", http.HandlerFunc(h.listProductFeedback))
	sub.Handle("POST /api/products/{id}/knowledge", http.HandlerFunc(h.postProductKnowledge))
	sub.Handle("GET /api/products/{id}/knowledge/{entryId}", http.HandlerFunc(h.getProductKnowledgeEntry))
	sub.Handle("PATCH /api/products/{id}/knowledge/{entryId}", http.HandlerFunc(h.patchProductKnowledgeEntry))
	sub.Handle("DELETE /api/products/{id}/knowledge/{entryId}", http.HandlerFunc(h.deleteProductKnowledgeEntry))
	sub.Handle("GET /api/products/{id}/knowledge", http.HandlerFunc(h.listProductKnowledge))
	sub.Handle("PATCH /api/product-feedback/{id}", http.HandlerFunc(h.patchProductFeedback))
	sub.Handle("GET /api/products/{id}/swipe-history", http.HandlerFunc(h.listSwipeHistory))
	sub.Handle("POST /api/products/{id}/preference-model/recompute", http.HandlerFunc(h.postRecomputePreferenceModel))
	sub.Handle("GET /api/products/{id}/preference-model", http.HandlerFunc(h.getProductPreferenceModel))
	sub.Handle("PUT /api/products/{id}/preference-model", http.HandlerFunc(h.putProductPreferenceModel))
	sub.Handle("GET /api/products/{id}/product-schedule", http.HandlerFunc(h.getProductSchedule))
	sub.Handle("PATCH /api/products/{id}/product-schedule", http.HandlerFunc(h.patchProductSchedule))
	sub.Handle("GET /api/products/{id}/research-cycles", http.HandlerFunc(h.listProductResearchCycles))
	sub.Handle("GET /api/products/{id}/tasks", http.HandlerFunc(h.listProductTasks))
	sub.Handle("GET /api/products/{id}/costs/breakdown", http.HandlerFunc(h.productCostBreakdown))
	sub.Handle("PATCH /api/products/{id}/cost-caps", http.HandlerFunc(h.patchProductCostCaps))
	sub.Handle("GET /api/products/{id}/convoys", http.HandlerFunc(h.listProductConvoys))
	sub.Handle("GET /api/products/{id}/merge-queue", http.HandlerFunc(h.listProductMergeQueue))
	sub.Handle("GET /api/products/{id}/agent-health", http.HandlerFunc(h.listProductAgentHealth))
	sub.Handle("GET /api/products/{id}/stalled-tasks", http.HandlerFunc(h.listStalledTasks))
	sub.Handle("PATCH /api/ideas/{id}", http.HandlerFunc(h.patchIdea))
	sub.Handle("POST /api/ideas/{id}/swipe", http.HandlerFunc(h.swipe))
	sub.Handle("POST /api/ideas/{id}/promote-maybe", http.HandlerFunc(h.promoteMaybe))
	sub.Handle("POST /api/tasks", http.HandlerFunc(h.createTask))
	sub.Handle("GET /api/tasks/{id}", http.HandlerFunc(h.getTask))
	sub.Handle("PATCH /api/tasks/{id}", http.HandlerFunc(h.patchTask))
	sub.Handle("POST /api/tasks/{id}/plan/approve", http.HandlerFunc(h.approvePlan))
	sub.Handle("POST /api/tasks/{id}/plan/reject", http.HandlerFunc(h.rejectPlan))
	sub.Handle("POST /api/tasks/{id}/dispatch", http.HandlerFunc(h.dispatchTask))
	sub.Handle("POST /api/tasks/{id}/merge-queue", http.HandlerFunc(h.enqueueMergeQueue))
	sub.Handle("DELETE /api/tasks/{id}/merge-queue", http.HandlerFunc(h.cancelMergeQueue))
	sub.Handle("POST /api/tasks/{id}/merge-queue/complete", http.HandlerFunc(h.completeMergeQueue))
	sub.Handle("POST /api/tasks/{id}/merge-queue/resolve", http.HandlerFunc(h.resolveMergeQueueByTask))
	sub.Handle("POST /api/merge-queue/{id}/resolve", http.HandlerFunc(h.resolveMergeQueueByRow))
	sub.Handle("POST /api/tasks/{id}/workspace/git-worktree", http.HandlerFunc(h.prepareGitWorktree))
	sub.Handle("GET /api/tasks/{id}/agent-health", http.HandlerFunc(h.getTaskAgentHealth))
	sub.Handle("PATCH /api/tasks/{id}/agent-health", http.HandlerFunc(h.patchTaskAgentHealth))
	sub.Handle("POST /api/tasks/{id}/pull-request", http.HandlerFunc(h.openPullRequest))
	sub.Handle("GET /api/tasks/{id}/checkpoints", http.HandlerFunc(h.listTaskCheckpoints))
	sub.Handle("POST /api/tasks/{id}/checkpoint/restore", http.HandlerFunc(h.restoreTaskCheckpoint))
	sub.Handle("POST /api/tasks/{id}/checkpoint", http.HandlerFunc(h.checkpoint))
	sub.Handle("POST /api/tasks/{id}/complete", http.HandlerFunc(h.completeTask))
	sub.Handle("POST /api/tasks/{id}/stall-nudge", http.HandlerFunc(h.nudgeStallTask))
	sub.Handle("GET /api/tasks/{id}/convoy", http.HandlerFunc(h.getTaskConvoyMC))
	sub.Handle("POST /api/tasks/{id}/convoy", http.HandlerFunc(h.postTaskConvoyMC))
	sub.Handle("PATCH /api/tasks/{id}/convoy", http.HandlerFunc(h.patchTaskConvoyMC))
	sub.Handle("DELETE /api/tasks/{id}/convoy", http.HandlerFunc(h.deleteTaskConvoyMC))
	sub.Handle("GET /api/tasks/{id}/convoy/progress", http.HandlerFunc(h.getTaskConvoyProgressMC))
	sub.Handle("POST /api/tasks/{id}/convoy/dispatch", http.HandlerFunc(h.postTaskConvoyDispatchMC))
	sub.Handle("POST /api/tasks/{id}/convoy/subtasks", http.HandlerFunc(h.postTaskConvoySubtasksMC))
	sub.Handle("POST /api/tasks/{id}/chat", http.HandlerFunc(h.postTaskChat))
	sub.Handle("GET /api/tasks/{id}/chat", http.HandlerFunc(h.getTaskChat))
	sub.Handle("GET /api/products/{id}/chat-queue", http.HandlerFunc(h.listProductChatQueue))
	sub.Handle("POST /api/products/{id}/chat-queue/{messageId}/ack", http.HandlerFunc(h.ackProductChatQueue))
	sub.Handle("POST /api/convoys", http.HandlerFunc(h.createConvoy))
	sub.Handle("GET /api/convoys/{id}", http.HandlerFunc(h.getConvoy))
	sub.Handle("GET /api/convoys/{id}/graph", http.HandlerFunc(h.getConvoyGraph))
	sub.Handle("GET /api/convoys/{id}/mail", http.HandlerFunc(h.listConvoyMail))
	sub.Handle("POST /api/convoys/{id}/mail", http.HandlerFunc(h.postConvoyMail))
	sub.Handle("POST /api/convoys/{id}/dispatch-ready", http.HandlerFunc(h.dispatchConvoy))
	// MC-compat singular paths (locked design §1).
	sub.Handle("POST /api/convoy", http.HandlerFunc(h.createConvoy))
	sub.Handle("GET /api/convoy/{id}", http.HandlerFunc(h.getConvoy))
	sub.Handle("GET /api/convoy/{id}/graph", http.HandlerFunc(h.getConvoyGraph))
	sub.Handle("GET /api/convoy/{id}/mail", http.HandlerFunc(h.listConvoyMail))
	sub.Handle("POST /api/convoy/{id}/mail", http.HandlerFunc(h.postConvoyMail))
	sub.Handle("POST /api/convoy/{id}/dispatch-ready", http.HandlerFunc(h.dispatchConvoy))
	sub.Handle("POST /api/costs", http.HandlerFunc(h.recordCost))
	sub.Handle("POST /api/workspace/ports", http.HandlerFunc(h.allocateWorkspacePort))
	sub.Handle("DELETE /api/workspace/ports/{port}", http.HandlerFunc(h.releaseWorkspacePort))
	sub.Handle("GET /api/gateway-endpoints", http.HandlerFunc(h.listGatewayEndpoints))
	sub.Handle("POST /api/gateway-endpoints", http.HandlerFunc(h.createGatewayEndpoint))
	sub.Handle("PATCH /api/gateway-endpoints/{id}", http.HandlerFunc(h.patchGatewayEndpoint))
	sub.Handle("POST /api/gateway-endpoints/{id}/test-connection", http.HandlerFunc(h.postGatewayEndpointTestConnection))
	sub.Handle("DELETE /api/gateway-endpoints/{id}", http.HandlerFunc(h.deleteGatewayEndpoint))
	sub.Handle("GET /api/research-hubs", http.HandlerFunc(h.listResearchHubs))
	sub.Handle("POST /api/research-hubs", http.HandlerFunc(h.createResearchHub))
	sub.Handle("PATCH /api/research-hubs/{id}", http.HandlerFunc(h.patchResearchHub))
	sub.Handle("DELETE /api/research-hubs/{id}", http.HandlerFunc(h.deleteResearchHub))
	sub.Handle("POST /api/research-hubs/{id}/test", http.HandlerFunc(h.postResearchHubTest))
	sub.Handle("POST /api/research-hubs/{id}/invoke", http.HandlerFunc(h.postResearchHubInvoke))
	sub.Handle("GET /api/research-system-settings", http.HandlerFunc(h.getResearchSystemSettings))
	sub.Handle("PATCH /api/research-system-settings", http.HandlerFunc(h.patchResearchSystemSettings))
	sub.Handle("GET /api/fleet/identities", http.HandlerFunc(h.listFleetIdentities))
	sub.Handle("GET /api/fleet/identities/{id}", http.HandlerFunc(h.getFleetIdentity))
	sub.Handle("POST /api/fleet/refresh", http.HandlerFunc(h.postFleetRefresh))
	sub.Handle("GET /api/fleet/geo-summary", http.HandlerFunc(h.fleetGeoSummary))
	sub.Handle("GET /api/agents", http.HandlerFunc(h.listAgents))
	sub.Handle("POST /api/agents", http.HandlerFunc(h.registerExecutionAgent))
	sub.Handle("GET /api/agents/{id}/mailbox", http.HandlerFunc(h.listAgentMailbox))
	sub.Handle("POST /api/agents/{id}/mailbox", http.HandlerFunc(h.postAgentMailbox))
	sub.Handle("POST /api/openclaw/proxy", http.HandlerFunc(h.openclawStub))
	sub.Handle("GET /api/workspaces", http.HandlerFunc(h.workspacesView))
	sub.Handle("GET /api/operations-log", http.HandlerFunc(h.listOperationsLog))
	sub.Handle("GET /api/settings", http.HandlerFunc(h.settingsStub))
	sub.Handle("POST /api/nlp/tfidf-suggest-tags", http.HandlerFunc(h.postTfidfSuggestTags))

	mux.Handle("/", AuthMiddleware(cfg, sub))

	var handler http.Handler = mux
	if cfg.AccessLog {
		handler = AccessLogMiddleware(slog.Default(), handler)
	}
	handler = RequestIDMiddleware(handler)
	return handler
}
